=head1 Mail2CV.com

This is the script that powers Mail2CV.com.

It is a service that allows adding tasks to your Checkvist.com list via email.

=head2 Running

You will need a fairly modern perl and some modules from CPAN:

uni::perl, WebService::Simple, Email::MIME, Email::Address

You will also need to set up some email forwarding to feed incoming emails to the script.
I use a catch-all virtual domain in Postfix and a simple ~/.forward with a pipe.
